dist: bionic
language: python
python:
  - 3.7

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo jq '.experimental = true' /etc/docker/daemon.json > /tmp/daemon.json && sudo mv /tmp/daemon.json /etc/docker/daemon.json
  - sudo service docker restart
  - docker buildx create --name mybuilder --driver docker-container --driver-opt image=moby/buildkit:master,network=host
  - docker buildx use mybuilder
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx inspect --bootstrap
  - docker run -d -p 5000:5000 --restart=always --name registry registry:2
  - docker pull ubuntu:16.04
  - docker pull ubuntu:18.04
  - docker pull ubuntu:20.04
  - docker pull node:12.16
  - docker pull yukinying/chrome-headless-browser-selenium:latest
  - docker pull alpine:3.11.6
  - docker pull solita/ubuntu-systemd:latest
  - BUILDKIT_PROGRESS=plain make run-tests-python
  - BUILDKIT_PROGRESS=plain make run-tests-angular

install:
  - docker version
  - travis_wait 30 BUILDKIT_PROGRESS=plain make

script:
  - BUILDKIT_PROGRESS=plain make run-tests-e2e SEEDSYNC_VERSION=latest SEEDSYNC_ARCH=amd64
  - BUILDKIT_PROGRESS=plain make run-tests-e2e SEEDSYNC_VERSION=latest SEEDSYNC_ARCH=arm64
  - BUILDKIT_PROGRESS=plain make run-tests-e2e SEEDSYNC_VERSION=latest SEEDSYNC_ARCH=arm/v7
  - BUILDKIT_PROGRESS=plain make run-tests-e2e SEEDSYNC_DEB=`readlink -f build/*.deb` SEEDSYNC_OS=ubu1604
  - BUILDKIT_PROGRESS=plain make run-tests-e2e SEEDSYNC_DEB=`readlink -f build/*.deb` SEEDSYNC_OS=ubu1804
  - BUILDKIT_PROGRESS=plain make run-tests-e2e SEEDSYNC_DEB=`readlink -f build/*.deb` SEEDSYNC_OS=ubu2004
